# https://github.com/actions/labeler
---
"⚙️ configuration":
    - packages/*/source/**/*
    - packages/markdownlint/markdownlint.json
    - packages/typescript/tsconfig.json

"📓 documentation":
    - README.md
    - packages/*/README.md

"🧹 formatter":
    - packages/prettier/**/*

"🕵️ linter":
    - packages/eslint/**/*
    - packages/markdownlint/**/*
    - packages/stylelint/**/*

"🧰 monorepo":
    - .github/**/*

"🎉 release":
    - packages/*/CHANGELOG.md

"🔧 tool":
    - packages/typescript/**/*
