# https://github.com/actions/labeler
---
"🏗️ continuous integration":
    - .github/**/*

"📓 documentation":
    - README.md
    - packages/*/README.md

"📦 package:eslint-config":
    - packages/prettier/**/*

"📦 package:markdownlint-config":
    - packages/prettier/**/*

"📦 package:prettier-config":
    - packages/prettier/**/*

"📦 package:stylelint-config":
    - packages/stylelint/**/*

"📦 package:typescript-config":
    - packages/typescript/**/*

"🎉 release":
    - packages/*/CHANGELOG.md
