# https://pnpm.io/pnpm-workspace_yaml
---
link-workspace-packages: true
packages:
    - "helpers/**"
    - "packages/**"
prefer-workspace-packages: true
shared-workspace-lockfile: true
save-workspace-protocol: true
