---
name: Build

on:
    pull_request:
        branches: [main]
        types: [opened, synchronize, reopened]
    push:
        branches: [main]

concurrency:
    group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
    cancel-in-progress: true

defaults:
    run:
        shell: bash

env:
    CI: true
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    PNPM_CACHE_FOLDER: .pnpm-store

jobs:
    sonarcloud:
        runs-on: ${{ matrix.os }}
        steps:
            - name: Checkout to ${{ github.repository }} repository
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: SonarCloud - Automatic code review, testing, inspection & auditing
              uses: sonarsource/sonarcloud-github-action@master
              with:
                  projectBaseDir: my-custom-directory
                  args: >
                      -Dsonar.organization=terminal-nerds
                      -Dsonar.projectKey=terminal-nerds_configs
                      -Dsonar.python.coverage.reportPaths=coverage.xml
                      -Dsonar.sources=.
                      -Dsonar.verbose=true

    build:
        name: Build packages
        needs: [sonarcloud]
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                node-version: [16.x]
                pnpm-version: [6.x]
                os: [ubuntu-latest]
        steps:
            - name: Checkout to ${{ github.repository }} repository
              uses: actions/checkout@v2
              with:
                  ref: ${{ github.head_ref }}
                  fetch-depth: 0

            - name: Use pnpm version ${{ matrix.pnpm-version }}
              uses: pnpm/action-setup@v2.0.1
              with:
                  version: ${{ matrix.pnpm-version }}
                  run_install: true

            - name: Setup Node.js version ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"

            - name: Execute package.json script "build"
              run: pnpm build

            - name: "Upload built packages"
              uses: actions/upload-artifact@v2
              with:
                  if-no-files-found: error
                  name: built-packages
                  path: packages/*/dist/
        timeout-minutes: 5
