---
name: Continuous Integration

on:
    push:
    pull_request:
    workflow_dispatch:
        branches: [main, develop]

concurrency:
    group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
    cancel-in-progress: true

env:
    CI: true
    PNPM_CACHE_FOLDER: .pnpm-store

permissions:
    checks: write
    contents: write

jobs:
    build:
        name: Build packages
        runs-on: ${{ matrix.os }}
        timeout-minutes: 5
        strategy:
            matrix:
                node-version: [16.x]
                pnpm-version: [6.x]
                os: [ubuntu-latest]

        steps:
            - name: Checkout to ${{ github.repository }} repository
              uses: actions/checkout@v2
              with:
                  ref: ${{ github.head_ref }}
                  fetch-depth: 0

            - name: Use pnpm version ${{ matrix.pnpm-version }}
              uses: pnpm/action-setup@v2.0.1
              with:
                  version: ${{ matrix.pnpm-version }}
                  run_install: true

            - name: Setup Node.js version ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"

            - name: Execute package.json script "build"
              run: pnpm build

    lint:
        name: Run linters
        needs: [build]
        runs-on: ${{ matrix.os }}
        timeout-minutes: 5
        strategy:
            matrix:
                node-version: [16.x]
                pnpm-version: [6.x]
                os: [ubuntu-latest]
        steps:
            - name: Checkout to ${{ github.repository }} repository
              uses: actions/checkout@v2
              with:
                  ref: ${{ github.head_ref }}
                  fetch-depth: 0

            - name: Use pnpm version ${{ matrix.pnpm-version }}
              uses: pnpm/action-setup@v2.0.1
              with:
                  version: ${{ matrix.pnpm-version }}
                  run_install: true

            - name: Setup Node.js version ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"

            - name: Run linters (ESLint, Prettier)
              uses: wearerequired/lint-action@v1.10.0
              with:
                  eslint: true
                  eslint_command_prefix: DEBUG="eslint:cli-engine"
                  eslint_extensions: json,ts,yaml,yml
                  prettier: true
                  git_name: github-actions[bot]
                  git_email: github-actions[bot]@users.noreply.github.com
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  neutral_check_on_warning: false

            - name: Run markdownlint
              run: pnpm markdownlint . --dot --ignore-path .gitignore
