---
name: Linting

on:
    workflow_run:
        types: [completed]
        workflows: [Build packages]

concurrency:
    group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
    cancel-in-progress: true

defaults:
    run:
        shell: bash

env:
    CI: true
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    PNPM_CACHE_FOLDER: .pnpm-store

jobs:
    eslint:
        name: ESLint - statically analyze the JavaScript code
        needs: [build]
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                node-version: [16.x]
                pnpm-version: [6.x]
                os: [ubuntu-latest]
        steps:
            - name: Checkout to ${{ github.repository }} repository
              uses: actions/checkout@v2
              with:
                  ref: ${{ github.head_ref }}
                  fetch-depth: 0

            - name: Use pnpm version ${{ matrix.pnpm-version }}
              uses: pnpm/action-setup@v2.0.1
              with:
                  version: ${{ matrix.pnpm-version }}
                  run_install: true

            - name: Setup Node.js version ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"

            - name: Download built packages
              uses: actions/download-artifact@v2

            - name: Extract built packages
              run: ./.github/extract-built-packages.sh

            - name: Execute ESLint
              run: >
                  DEBUG="eslint:cli-engine"
                  pnpm eslint .
                  --ext .json,.ts,.yaml,.yml,
        timeout-minutes: 5

    markdownlint:
        name: markdownlint - validate markdown files
        needs: [build]
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                node-version: [16.x]
                pnpm-version: [6.x]
                os: [ubuntu-latest]
        timeout-minutes: 5
        steps:
            - name: Checkout to ${{ github.repository }} repository
              uses: actions/checkout@v2
              with:
                  ref: ${{ github.head_ref }}
                  fetch-depth: 0

            - name: Use pnpm version ${{ matrix.pnpm-version }}
              uses: pnpm/action-setup@v2.0.1
              with:
                  version: ${{ matrix.pnpm-version }}
                  run_install: true

            - name: Setup Node.js version ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"

            - name: Download built packages
              uses: actions/download-artifact@v2

            - name: Extract built packages
              run: ./.github/extract-built-packages.sh

            - name: Execute markdownlint
              run: >
                  pnpm markdownlint .
                  --dot
                  --ignore-path ".gitignore"
                  --ignore "./.changeset/*.md"

    prettier:
        name: Prettier - check code formatting style
        needs: [build]
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                node-version: [16.x]
                pnpm-version: [6.x]
                os: [ubuntu-latest]
        steps:
            - name: Checkout to ${{ github.repository }} repository
              uses: actions/checkout@v2
              with:
                  ref: ${{ github.head_ref }}
                  fetch-depth: 0

            - name: Use pnpm version ${{ matrix.pnpm-version }}
              uses: pnpm/action-setup@v2.0.1
              with:
                  version: ${{ matrix.pnpm-version }}
                  run_install: true

            - name: Setup Node.js version ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"

            - name: Download built packages
              uses: actions/download-artifact@v2

            - name: Extract built packages
              run: ./.github/extract-built-packages.sh

            - name: Execute Prettier script
              run: >
                  pnpm pretty-quick
                  --branch HEAD~${{ github.event.pull_request.commits }}
                  --check
                  --verbose
        timeout-minutes: 5
