# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
---
name: Maintenance

on:
    issues:
    pull_request_target:
        branches: [main]

concurrency:
    group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
    cancel-in-progress: true

defaults:
    run:
        shell: bash

env:
    CI: true

jobs:
    codesee-map:
        name: Pull Requests - ${{ github.event_name }} - ${{ github.event }}
        # https://github.com/terminal-nerds/.github/blob/main/.github/workflows/codesee-map.yml
        uses: terminal-nerds/.github/.github/workflows/codesee-map.yml@main

    greetings:
        name: Maintenance
        # https://github.com/terminal-nerds/.github/blob/main/.github/workflows/greetings.yml
        uses: terminal-nerds/.github/.github/workflows/greetings.yml@main

    issue-labels:
        name: Maintenance
        # https://github.com/terminal-nerds/.github/blob/main/.github/workflows/issue-labels.yml
        uses: terminal-nerds/.github/.github/workflows/issue-labels.yml@main

    pull-request-labels:
        name: Maintenance
        # https://github.com/terminal-nerds/.github/blob/main/.github/workflows/pull-requests-labels.yml
        uses: terminal-nerds/.github/.github/workflows/pull-request-labels.yml@main
